# Exam on Artificial Neural Networks (ANN)

Welcome the Artificial Neural Networks (ANN) practical exam. In this exam, you will work on a classification task to predict the outcome of incidents involving buses. You are provided with a dataset that records breakdowns and delays in bus operations. Your task is to build, train, and evaluate an ANN model.

---

## Dataset Overview

### **Dataset:**
* Just run the command under the `Load Data` section to get the data downloaded and unzipped or you can access it [here](www.kaggle.com/datasets/khaledzsa/bus-breakdown-and-delays)

### **Dataset Name:** Bus Breakdown and Delays

### **Description:**  
The dataset contains records of incidents involving buses that were either running late or experienced a breakdown. Your task is to predict whether the bus was delayed or had a breakdown based on the features provided.

### **Features:**
The dataset contains the following columns:

- `School_Year`
- `Busbreakdown_ID`
- `Run_Type`
- `Bus_No`
- `Route_Number`
- `Reason`
- `Schools_Serviced`
- `Occurred_On`
- `Created_On`
- `Boro`
- `Bus_Company_Name`
- `How_Long_Delayed`
- `Number_Of_Students_On_The_Bus`
- `Has_Contractor_Notified_Schools`
- `Has_Contractor_Notified_Parents`
- `Have_You_Alerted_OPT`
- `Informed_On`
- `Incident_Number`
- `Last_Updated_On`
- `Breakdown_or_Running_Late` (Target Column)
- `School_Age_or_PreK`

## Load Data

In [275]:
!kaggle datasets download -d khaledzsa/bus-breakdown-and-delays
!unzip bus-breakdown-and-delays.zip

Dataset URL: https://www.kaggle.com/datasets/khaledzsa/bus-breakdown-and-delays
License(s): unknown
bus-breakdown-and-delays.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  bus-breakdown-and-delays.zip
replace Bus_Breakdown_and_Delays.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

## Importing Libraries

In [276]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers, models
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## Exploratory Data Analysis (EDA)
This could include:
* **Inspect the dataset**

* **Dataset structure**

* **Summary statistics**

* **Check for missing values**

* **Distribution of features**

* **Categorical feature analysis**

* **Correlation matrix**

* **Outlier detection**

And add more as needed!

In [277]:
df = pd.read_csv('Bus_Breakdown_and_Delays.csv')
df.head()

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
0,2015-2016,1224901,Pre-K/EI,811,1,Other,C353,10/26/2015 08:30:00 AM,10/26/2015 08:40:00 AM,Bronx,...,10MINUTES,5,Yes,Yes,No,10/26/2015 08:40:00 AM,NaN,10/26/2015 08:40:39 AM,Running Late,Pre-K
1,2015-2016,1225098,Pre-K/EI,9302,1,Heavy Traffic,C814,10/27/2015 07:10:00 AM,10/27/2015 07:11:00 AM,Bronx,...,25 MINUTES,3,Yes,Yes,No,10/27/2015 07:11:00 AM,NaN,10/27/2015 07:11:22 AM,Running Late,Pre-K
2,2015-2016,1215800,Pre-K/EI,358,2,Heavy Traffic,C195,09/18/2015 07:36:00 AM,09/18/2015 07:38:00 AM,Bronx,...,15 MINUTES,12,Yes,Yes,Yes,09/18/2015 07:38:00 AM,NaN,09/18/2015 07:38:44 AM,Running Late,Pre-K
3,2015-2016,1215511,Pre-K/EI,331,2,Other,C178,09/17/2015 08:08:00 AM,09/17/2015 08:12:00 AM,Bronx,...,10 minutes,11,Yes,Yes,Yes,09/17/2015 08:12:00 AM,NaN,09/17/2015 08:12:08 AM,Running Late,Pre-K
4,2015-2016,1215828,Pre-K/EI,332,2,Other,S176,09/18/2015 07:39:00 AM,09/18/2015 07:45:00 AM,Bronx,...,10MINUTES,12,Yes,Yes,No,09/18/2015 07:45:00 AM,NaN,09/18/2015 07:56:40 AM,Running Late,Pre-K

In [278]:
df.sample(10)

,School_Year,Busbreakdown_ID,Run_Type,Bus_No,Route_Number,Reason,Schools_Serviced,Occurred_On,Created_On,Boro,...,How_Long_Delayed,Number_Of_Students_On_The_Bus,Has_Contractor_Notified_Schools,Has_Contractor_Notified_Parents,Have_You_Alerted_OPT,Informed_On,Incident_Number,Last_Updated_On,Breakdown_or_Running_Late,School_Age_or_PreK
20760,2015-2016,1240355,Special Ed AM Run,VN74104,N866,Heavy Traffic,75907,01/08/2016 06:41:00 AM,01/08/2016 06:49:00 AM,All Boroughs,...,30mins,0,Yes,Yes,Yes,01/08/2016 06:49:00 AM,NaN,01/08/2016 06:49:08 AM,Running Late,School-Age
98089,2016-2017,1319090,General Ed AM Run,52266,K8467,Heavy Traffic,17006,01/27/2017 07:15:00 AM,01/27/2017 07:23:00 AM,Brooklyn,...,45 min,0,Yes,No,No,01/27/2017 07:23:00 AM,NaN,01/27/2017 07:23:00 AM,Running Late,School-Age
77555,2016-2017,1298320,Special Ed AM Run,639,M430,Heavy Traffic,02031,11/07/2016 07:50:00 AM,11/07/2016 07:54:00 AM,Manhattan,...,30 min,2,Yes,Yes,No,11/07/2016 07:54:00 AM,NaN,11/07/2016 07:54:43 AM,Running Late,School-Age
114584,2016-2017,1335815,Special Ed PM Run,21107,K096,Late return from Field Trip,13020,03/29/2017 02:10:00 PM,03/29/2017 02:15:00 PM,Brooklyn,...,30 min,0,Yes,Yes,No,03/29/2017 02:15:00 PM,NaN,03/29/2017 02:15:10 PM,Running Late,School-Age
43585,2015-2016,1263871,Special Ed AM Run,122,W929,Heavy Traffic,75871,04/20/2016 08:41:00 AM,04/20/2016 08:43:00 AM,Westchester,...,15MINS,6,Yes,No,No,04/20/2016 08:43:00 AM,NaN,04/20/2016 08:43:51 AM,Running Late,School-Age
73139,2016-2017,1293858,Special Ed PM Run,1432PM,N954,Heavy Traffic,75628,10/20/2016 02:49:00 PM,10/20/2016 02:50:00 PM,Nassau County,...,30,0,Yes,Yes,No,10/20/2016 02:50:00 PM,NaN,10/20/2016 02:50:40 PM,Running Late,School-Age
111051,2016-2017,1332275,Pre-K/EI,9310,1,Heavy Traffic,C465,03/20/2017 08:03:00 AM,03/20/2017 08:06:00 AM,Bronx,...,20 MINS,9,Yes,Yes,No,03/20/2017 08:06:00 AM,NaN,03/20/2017 08:06:08 AM,Running Late,Pre-K
42804,2015-2016,1263090,Special Ed AM Run,NI1490,K119,Other,21095,04/18/2016 06:40:00 AM,04/18/2016 07:03:00 AM,Brooklyn,...,30 MIN,3,Yes,Yes,No,04/18/2016 07:03:00 AM,NaN,04/18/2016 07:07:57 AM,Running Late,School-Age
1144,2015-2016,1226257,Special Ed AM Run,2830,L972,Other,19213,10/30/2015 06:19:00 AM,10/30/2015 06:21:00 AM,Brooklyn,...,10 MIN,0,Yes,Yes,Yes,10/30/2015 06:21:00 AM,NaN,10/30/2015 06:22:02 AM,Running Late,School-Age
29391,2015-2016,1249373,Special Ed AM Run,NI4483,K201,Heavy Traffic,14157,02/09/2016 07:20:00 AM,02/09/2016 07:28:00 AM,Brooklyn,...,45 MIN,8,Yes,Yes,No,02/09/2016 07:28:00 AM,NaN,02/09/2016 07:28:13 AM,Running Late,School-Age

In [279]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147972 entries, 0 to 147971
Data columns (total 21 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   School_Year                      147972 non-null  object
 1   Busbreakdown_ID                  147972 non-null  int64
 2   Run_Type                         147883 non-null  object
 3   Bus_No                           147972 non-null  object
 4   Route_Number                     147884 non-null  object
 5   Reason                           147870 non-null  object
 6   Schools_Serviced                 147972 non-null  object
 7   Occurred_On                      147972 non-null  object
 8   Created_On                       147972 non-null  object
 9   Boro                             141654 non-null  object
 10  Bus_Company_Name                 147972 non-null  object
 11  How_Long_Delayed                 126342 non-null  object
 12  Number_Of_Students_On_The_Bus    147972 non-null  int64
 13  Has_Contractor_Notified_Schools  147972 non-null  object
 14  Has_Contractor_Notified_Parents  147972 non-null  object
 15  Have_You_Alerted_OPT             147972 non-null  object
 16  Informed_On                      147972 non-null  object
 17  Incident_Number                  5632 non-null    object
 18  Last_Updated_On                  147972 non-null  object
 19  Breakdown_or_Running_Late        147972 non-null  object
 20  School_Age_or_PreK               147972 non-null  object
dtypes: int64(2), object(19)
memory usage: 23.7+ MB

In [280]:
df.describe()

       Busbreakdown_ID  Number_Of_Students_On_The_Bus
count     1.479720e+05                  147972.000000
mean      1.287779e+06                       3.590071
std       4.324338e+04                      55.365859
min       1.212681e+06                       0.000000
25%       1.250438e+06                       0.000000
50%       1.287844e+06                       0.000000
75%       1.325191e+06                       4.000000
max       1.362605e+06                    9007.000000

In [281]:
df.shape

(147972, 21)

In [282]:
df.columns

Index(['School_Year', 'Busbreakdown_ID', 'Run_Type', 'Bus_No', 'Route_Number',
       'Reason', 'Schools_Serviced', 'Occurred_On', 'Created_On', 'Boro',
       'Bus_Company_Name', 'How_Long_Delayed', 'Number_Of_Students_On_The_Bus',
       'Has_Contractor_Notified_Schools', 'Has_Contractor_Notified_Parents',
       'Have_You_Alerted_OPT', 'Informed_On', 'Incident_Number',
       'Last_Updated_On', 'Breakdown_or_Running_Late', 'School_Age_or_PreK'],
      dtype='object')

In [283]:
df.isna().sum()

School_Year                             0
Busbreakdown_ID                         0
Run_Type                               89
Bus_No                                  0
Route_Number                           88
Reason                                102
Schools_Serviced                        0
Occurred_On                             0
Created_On                              0
Boro                                 6318
Bus_Company_Name                        0
How_Long_Delayed                    21630
Number_Of_Students_On_The_Bus           0
Has_Contractor_Notified_Schools         0
Has_Contractor_Notified_Parents         0
Have_You_Alerted_OPT                    0
Informed_On                             0
Incident_Number                    142340
Last_Updated_On                         0
Breakdown_or_Running_Late               0
School_Age_or_PreK                      0
dtype: int64

## Data Preprocessing
This could include:

* **Handle Missing Values**
    * Impute missing values or drop them.

* **Encode Categorical Variables**
    * One-hot encoding
    * Label encoding

* **Scale and Normalize Data**
    * Standardization (Z-score)
    * Min-Max scaling

* **Feature Engineering**
    * Create new features
    * Feature selection

* **Handle Imbalanced Data**
    * Oversampling
    * Undersampling

* **Handle Outliers**
    * Remove outliers
    * Transform outliers

* **Remove Duplicates**
    * Remove redundant or duplicate data


And add more as needed!

Please treat these as suggestions. Feel free to use your judgment for the rest.

In [284]:
df.isna().sum()

School_Year                             0
Busbreakdown_ID                         0
Run_Type                               89
Bus_No                                  0
Route_Number                           88
Reason                                102
Schools_Serviced                        0
Occurred_On                             0
Created_On                              0
Boro                                 6318
Bus_Company_Name                        0
How_Long_Delayed                    21630
Number_Of_Students_On_The_Bus           0
Has_Contractor_Notified_Schools         0
Has_Contractor_Notified_Parents         0
Have_You_Alerted_OPT                    0
Informed_On                             0
Incident_Number                    142340
Last_Updated_On                         0
Breakdown_or_Running_Late               0
School_Age_or_PreK                      0
dtype: int64

In [285]:
df = df.drop(['Busbreakdown_ID','Incident_Number','How_Long_Delayed','Boro','Bus_No','Route_Number'], axis=1) # useless coulmns or having too many null values

In [286]:
label_encoder = LabelEncoder()
df['Breakdown_or_Running_Late'] = label_encoder.fit_transform(df['Breakdown_or_Running_Late'])

In [287]:
df.dropna(inplace=True)

In [288]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
df_encoded = pd.get_dummies(df, columns=['School_Year', 'Run_Type', 'Reason', 'Bus_Company_Name',
                                 'Has_Contractor_Notified_Schools', 'Has_Contractor_Notified_Parents',
                                 'Have_You_Alerted_OPT', 'School_Age_or_PreK'])

In [289]:
df.columns

Index(['School_Year', 'Run_Type', 'Reason', 'Schools_Serviced', 'Occurred_On',
       'Created_On', 'Bus_Company_Name', 'Number_Of_Students_On_The_Bus',
       'Has_Contractor_Notified_Schools', 'Has_Contractor_Notified_Parents',
       'Have_You_Alerted_OPT', 'Informed_On', 'Last_Updated_On',
       'Breakdown_or_Running_Late', 'School_Age_or_PreK'],
      dtype='object')

In [290]:
# Select numerical columns for scaling
numerical_cols = ['Number_Of_Students_On_The_Bus']


from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
df_encoded[numerical_cols] = min_max_scaler.fit_transform(df_encoded[numerical_cols])

In [291]:
#def remove_outliers(df,column):
#   q1 = df[column].quantile(0.25)
#  q3 = df[column].quantile(0.75)
#  iqr = q3 - q1
#  lower_bound  = q1 - (1.5 * iqr)
#  upper_bound = q3 + (1.5 * iqr)
#  return df.loc[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

#for i in df.select_dtypes(exclude=['object']).columns:
#    df = remove_outliers(df,i)

In [292]:
df.duplicated().sum()

36

In [293]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

0

## Split the Dataset
Next, split the dataset into training, validation, and testing sets.

In [294]:
X = df_encoded.drop(['Breakdown_or_Running_Late','Last_Updated_On','Informed_On','Created_On','Occurred_On','Schools_Serviced'], axis=1)
y = df['Breakdown_or_Running_Late']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

ValueError: Found input variables with inconsistent numbers of samples: [147781, 147745]

In [ ]:
y

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

## Building the ANN Model
In this section, define the architecture of the ANN by specifying the number of layers, neurons, and activation functions.

In [ ]:
model = keras.Sequential([Dense(units=50, activation='relu'),
                          Dropout(0.2),
                          Dense(units=100, activation='relu'),
                          Dropout(0.2),
                          Dense(units=1, activation='sigmoid')
])

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True,
    )

## Compile the Model
Compile the ANN model by defining the optimizer, loss function, and evaluation metrics.

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['recall'])

## Training the Model
Train the ANN model using the training data.

In [ ]:
history = model.fit(X_train, y_train, epochs=200, validation_data=(X_val, y_val), callbacks=[early_stopping])

## Evaluate the Model
Evaluate the performance of the model on the test set.

In [ ]:
model.evaluate(X_val, y_val)

## Make Predictions
Use the trained model to make predictions on new or unseen data.

## Model Performance Visualization
Visualize the performance metrics such as accuracy and loss over the epochs.

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix
import numpy as np
accuracy_score = accuracy_score(y_test, np.argmax(model.predict(X_tes), axis=-1))
accuracy_score

## Save the Model
Save the trained model for submission.

## Project Questions:

1. **Data Preprocessing**: Explain why you chose your specific data preprocessing techniques (e.g., normalization, encoding). How did these techniques help prepare the data for training the model?
2. **Model Architecture**: Describe the reasoning behind your model’s architecture (e.g., the number of layers, type of layers, number of neurons, and activation functions). Why did you believe this architecture was appropriate for the problem at hand?
3. **Training Process**: Discuss why you chose your batch size, number of epochs, and optimizer. How did these choices affect the training process? Did you experiment with different values, and what were the outcomes?
4. **Loss Function and Metrics**: Why did you choose the specific loss function and evaluation metrics? How do they align with the objective of the task (e.g., regression vs classification)?
5. **Regularization Techniques**: If you used regularization techniques such as dropout or weight decay, explain why you implemented them and how they influenced the model's performance.
6. **Model Evaluation**: Justify your approach to evaluating the model. Why did you choose the specific performance metrics, and how do they reflect the model's success in solving the task?
7. **Model Tuning (If Done)**: Describe any tuning you performed (e.g., hyperparameter tuning) and why you felt it was necessary. How did these adjustments improve model performance?
8. **Overfitting and Underfitting**: Analyze whether the model encountered any overfitting or underfitting during training. What strategies could you implement to mitigate these issues?

### Answer Here:

All my answers depends on succsessing the train step.
Unfortunatlly, for some error the train doesn't executed ☹